name: ci

on:
  push:
    branches:
    - 'main'

jobs:
  docker:
    runs-on: bigrunner
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: dcl-godot-android-builder
        tags: ${{ github.sha }} ${{ inputs.docker-tag }}
        dockerfiles: |
          ./godot-android.Dockerfile
        build-args: |
          ${{ inputs.build-args }}
          COMMIT_HASH=${{ github.sha }}

    - name: Push To quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: quay.io/decentraland
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_TOKEN }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"