name: ci

on:
  push:
    branches:
    - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        file: godot-android.Dockerfile
        tags: kuruk/dcl-godot-android-builder:latest,kuruk/dcl-godot-android-builder:4.2
    - name: Build and push with Rust
      uses: docker/build-push-action@v5
      with:
        push: true
        file: godot-android-with-rust.Dockerfile
        tags: kuruk/dcl-godot-android-builder-rust:latest,kuruk/dcl-godot-android-builder-rust:4.2
